### ISSUE TITLE
Error: Cannot find module

### ISSUE THREAD

**Issue by JakubGIT** [geneseframework/complexity#52]
1. installed: `npm i -g @genese/cli` and `npm i -g genese cpx` (`npm i -g Genese Cpx` as per `README.md` didn't work)
2. called: `genese cpx ./src`
3. I get error:
```
Welcome to @genese cli
internal/modules/cjs/loader.js:905
  throw err;
  ^

Error: Cannot find module 'C:\Users\jkopecky\AppData\Roaming\npm\node_modules\@genese\cli\dist\src\\..\\..\\..\\complexity\\dist\\package.json'
Require stack:
- C:\Users\jkopecky\AppData\Roaming\npm\node_modules\@genese\cli\dist\src\index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
    at Function.Module._load (internal/modules/cjs/loader.js:746:27)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at Command.<anonymous> (C:\Users\jkopecky\AppData\Roaming\npm\node_modules\@genese\cli\dist\src\index.js:22:27)
    at Command.listener [as _actionHandler] (C:\Users\jkopecky\AppData\Roaming\npm\node_modules\@genese\cli\node_modules\commander\index.js:426:31)
    at Command._parseCommand (C:\Users\jkopecky\AppData\Roaming\npm\node_modules\@genese\cli\node_modules\commander\index.js:1002:14)
    at Command._dispatchSubcommand (C:\Users\jkopecky\AppData\Roaming\npm\node_modules\@genese\cli\node_modules\commander\index.js:953:18)
    at Command._parseCommand (C:\Users\jkopecky\AppData\Roaming\npm\node_modules\@genese\cli\node_modules\commander\index.js:970:12)
    at Command.parse (C:\Users\jkopecky\AppData\Roaming\npm\node_modules\@genese\cli\node_modules\commander\index.js:801:10) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'C:\\Users\\jkopecky\\AppData\\Roaming\\npm\\node_modules\\@genese\\cli\\dist\\src\\index.js'
  ]
}
```
`jkopecky` is my windows user
I tried to install locally, but I got an error too.

What do I do wrong?

thanks!

**Comment by geneseframework** [comment]
Hi Jakub, and thanks for your interest in our module.

There is a mistake on the README.md on the 1.1.15 version, which is now fixed in the 1.1.18 version.

You need to install Genese Cpx with the command line below :

npm i -g @genese/complexity

It is also possible that some other bugs persist in the actual version of Genese Cpx for the Windows users (problems with windows directory paths).

Thanks to tell us if all is ok now, or if some bugs persist !

Best,

Gilles

**Comment by JakubGIT** [comment]
Hi Gilles,

it works!! 

Thank you very much for the speedy reaction! :-)

**Comment by geneseframework** [comment]
Cool !

Out of curiosity, do you use it for a student project, or a professional one ? We like to know in what context our module is used, and if it is relevant for small or big projects.

Don't hesitate to give us your feedback ! :)

Best,
Gilles

**Comment by JakubGIT** [comment]
my bachelor thesis. It's a MS SharePoint web part with typescript and react - a small project. 

Kind regards

Jakub
